### ISSUE TITLE
Fails to launch, with exit code: has exited with code -1073741189 (0xc000027b)

### ISSUE THREAD

**Issue by Noemata** [TheXamlGuy/NotificationFlyout#1]
The sample app fails to launch, and exits with: has exited with code -1073741189 (0xc000027b)

I was only able to build the x64 version.  I get build errors for x86.

Any ideas on what might be wrong?

**Comment by TheXamlGuy** [comment]
Hi,

That will be because the NotificationFlyout.Sample.Wpf has no app identify. Ensure that you are debugging the NotificationFlyout.Package project, or you can right click the NotificationFlyout.Package project and deploy and run from the start menu. 

Hope that helps.

**Comment by Noemata** [comment]
Thanks, that did it.  Very nice.  I haven't worked with WPF in some time, and this particular combo of tech is completely new to me.  I can see I have a few things to learn.  I'd like to implement a right click context menu as well.

Looking to do something similar to: https://www.microsoft.com/store/apps/9NBXBP78896Q & https://www.microsoft.com/store/apps/9P0RP342JZMN in terms of the way the context menu works only (not the rest obviously).

Also, is there a way to configure the project to simplify testing?  Other XAML Island projects I've looked at seem much simpler.

**Comment by TheXamlGuy** [comment]
I have now fixed the issue where it wasn't possible to debug/test the project directly without the packaging requirements, it is now possible! :) 

I am still investigating what I will be doing for the context menu. I am currently deciding on whether I will be using the UWP MenuFlyout, or the WPF ContextMenu and restyling that.

**Comment by Noemata** [comment]
Thanks a bunch.  Build/Debug is way smoother.  Speaking for myself, I would prefer to see UWP used throughout, since that's the interesting part of this combination of tech.  Else you might as well stick to good old WPF and styling to get a UWP look.

Not sure, but I think the change in themes isn't as complete now when you select the light theme.

Lastly, I did decompile the above projects ( https://github.com/michalleptuch/media-mixer ).  To decompile, just install the app and load the main executable and DLL in dnSpy.  @michalleptuch has a simpler approach than yours, though yours is more complete.  You might want to take a look under the hood like I did.  The mechanism he uses for the context menu is surprisingly simple and works nicely.

I'm still trying to figure this out, so I can't contribute meaningfully to the merits of any given approach.  Your solution looks to be very complete!  I'm intrigued by your use of CsWin32 ... interesting.

**Comment by Noemata** [comment]
I should add, @michalleptuch has gone all out with using XAML Islands.  WPF is literally just the host.  Quite a nice design once you get all the bits right.

**Comment by TheXamlGuy** [comment]
Working on a fix for switching RequestedTheme, this was due to some of the bigger changes that I have made. 

Indeed the WPF app is just literally a host, same as for this project :)

I have a of respect for @michalleptuch, he has made some really beautiful and very useful apps by far. There are some issues with his apps like with regarding high DPI and multiple monitors where the ContextMenu and Flyout are appearing at the wrong place. Maybe tagging him here will get his attention! 😁

The main aim for this project is to make a reusable control where you will only have 2 projects in a solution, a WPF host, and the WPF app both where you'd simply reference a NuGet package for this control :)

**Comment by Noemata** [comment]
Agreed.  I'm going with your approach because it looks more robust.  Wasn't sure if you were aware of @michalleptuch 's work (for the sake of insight).  Please let me know if there's anything I can help with.  I'm hoping to get to a mix of NotificationFlyout for what it does, and how @michalleptuch does his main window design.  Puzzling over some of those details.  XAML Islands is a weird animal for someone that's lived mostly in UWP land for the past three years.

You may want to add a discussions section for banter like this.

**Comment by Noemata** [comment]
I'm mystified with how you came up with this for a UWP app?

```
  <PropertyGroup>
    <TargetFrameworks>uap10.0.19041</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
    <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
    <EnableXBindDiagnostics>false</EnableXBindDiagnostics>
    <LangVersion>9.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```

Where did you get your information on how to set this up?  There are less than a dozen projects on Github that have this arrangement?

**Comment by Noemata** [comment]
Answered my own questions about MSBuild.  You can close this issue.

**Comment by TheXamlGuy** [comment]
Closing issue as resolved.
