### ISSUE TITLE
In commit fd46a44 one of the project elements does not load.

### ISSUE THREAD

**Issue by Noemata** [TheXamlGuy/NotificationFlyout#5]
In commit https://github.com/TheXamlGuy/NotificationFlyout/commit/fd46a449880a50bac1b52b846e8be53b361a61ae

The Shared.UI project does not load as shown below:

![image](https://user-images.githubusercontent.com/6632315/107632865-149f9000-6c35-11eb-92ed-1f2a720e9e3a.png)

**Comment by Noemata** [comment]
Build fails also with:

Rebuild started...
1>------ Rebuild All started: Project: NotificationFlyout.Uwp.UI, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: NotificationFlyout.Wpf.UI, Configuration: Debug x64 ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
2>NotificationFlyout.Wpf.UI -> D:\Samples\XamlIslandsNew\NotificationFlyout-master\src\NotificationFlyout.Wpf.UI\bin\x64\Debug\netcoreapp3.1\NotificationFlyout.Wpf.UI.dll
1>NotificationFlyout.Uwp.UI -> D:\Samples\XamlIslandsNew\NotificationFlyout-master\src\NotificationFlyout.Uwp.UI\bin\Debug\uap10.0.19041\NotificationFlyout.Uwp.UI.dll
3>------ Rebuild All started: Project: NotificationFlyout.Uwp.UI.Controls, Configuration: Debug x64 ------
3>NotificationFlyout.Uwp.UI.Controls -> D:\Samples\XamlIslandsNew\NotificationFlyout-master\src\NotificationFlyout.Uwp.UI.Controls\bin\x64\Debug\uap10.0.19041\NotificationFlyout.Uwp.UI.Controls.dll
4>------ Rebuild All started: Project: NotificationFlyoutSample, Configuration: Debug x64 ------
5>------ Rebuild All started: Project: NotificationFlyout.Wpf.UI.Controls, Configuration: Debug x64 ------
4>D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyoutSample\App.xaml(7,73): XamlCompiler warning WMC1501: Version is for evaluation purposes only and is subject to change or removal in future updates.
4>  NotificationFlyoutSample -> D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyoutSample\bin\x64\Debug\NotificationFlyoutSample.exe
5>NotificationFlyout.Wpf.UI.Controls -> D:\Samples\XamlIslandsNew\NotificationFlyout-master\src\NotificationFlyout.Wpf.UI.Controls\bin\x64\Debug\netcoreapp3.1\NotificationFlyout.Wpf.UI.Controls.dll
6>------ Rebuild All started: Project: NotificationFlyoutSample.Host, Configuration: Debug x64 ------
6>D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyoutSample.Host\NotificationFlyoutSample.Host.csproj : error NU1104: Unable to find project 'D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyout.Shared.UI\NotificationFlyout.Shared.UI.csproj'. Check that the project reference is valid and that the project file exists.
6>Done building project "NotificationFlyoutSample.Host.csproj" -- FAILED.
7>------ Rebuild All started: Project: NotificationFlyoutSample.Package, Configuration: Debug x64 ------
7>D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyoutSample.Host\NotificationFlyoutSample.Host.csproj : error NU1104: Unable to find project 'D:\Samples\XamlIslandsNew\NotificationFlyout-master\samples\NotificationFlyout.Shared.UI\NotificationFlyout.Shared.UI.csproj'. Check that the project reference is valid and that the project file exists.
7>Done building project "NotificationFlyoutSample.Host.csproj" -- FAILED.
========== Rebuild All: 5 succeeded, 2 failed, 0 skipped ==========

**Comment by Noemata** [comment]
The Close context menu item (nice) does not close the app.  I didn't yet check to see if it's wired up.

**Comment by TheXamlGuy** [comment]
Hopefully sorted including a sample of closing the app. Let me know if all good and I'll close this issue off.

**Comment by Noemata** [comment]
Very nice.  Looks like you're about to cross the finish line!  You may want to switch NotificationFlyout.Wpf.UI.csproj to use MSBuild extras so it's consistent with the rest.  The only other thing I'd like to see is a mechanism for having an integrated main window as part of the NotificationFlyoutSample.Host solution.  It doesn't need to include UWP bits since the real purpose is to show how to get the best of both worlds, UWP and WPF.

I do remember there being challenges in keeping such a window invisible from the task bar when it is "closed".  I think I used a hidden window that faked a taskbar icon the last time I did something like this.

I realize that in most instances, the taskbar app will be used as a vehicle to lunch a main app, but having a sample with this built in does round the circle, I think.

You can close this issue.
